[package]
name = "shari-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
wasm-bindgen = "0.2.104"
shari = { path = ".." }
console_error_panic_hook = "0.1.6"

[lib]
crate-type = ["cdylib"]
