name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags:

      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.2.0

      - name: Build & Deploy
        run: |
          cd shari-playground
          npm ci
          npm run build
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}